version: '2'
services:

  nako:
    container_name: strat-nako
    networks: 
        nakonet:
            ipv4_address: 172.16.10.100
    image: coinvault/nako:latest
    command: strat
    ports: 
        - 9040:9000
    depends_on:
        - mongo
        - client

  client:
    container_name: strat-client
    networks: 
        nakonet:
            ipv4_address: 172.16.10.101
    image: stratisplatform/fullnode:StratisTestNet
    command: ["dotnet", "run", "-testnet", 
              "-server=1", "-maxblkmem=2", "-txindex=1",
              "-rpcallowip=172.16.10.100", "-rpcbind=172.16.10.101", "-rpcport=5000", "-rpcuser=rpcuser", "-rpcpassword=rpcpassword"]
    ports: 
        - 5040:5000
        - 26178:26178

  mongo:
    container_name: strat-mongo
    networks: 
        nakonet:
            ipv4_address: 172.16.10.102
    image: mongo:3.2

networks:
  nakonet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.10.0/24